# Generated by Django 2.0.7 on 2018-07-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False, verbose_name='gid')),
                ('gname', models.CharField(max_length=200, unique=True)),
                ('g_create_date', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miwang', models.IntegerField(default=0)),
                ('mifei', models.IntegerField(default=0)),
                ('mifen', models.IntegerField(default=0)),
                ('mixiaozhu', models.IntegerField(default=0)),
                ('p_create_date', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('pgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Group')),
            ],
        ),
    ]
