# Generated by Django 2.0.7 on 2018-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ditui',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='fenxiang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='huifang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='linshe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='shiyonzhang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='wangan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='yingliu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='zhaoan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='zhibang',
            field=models.IntegerField(default=0),
        ),
    ]
