# Generated by Django 2.0.7 on 2018-08-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_person_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('openid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
    ]
