# Generated by Django 2.0.7 on 2018-08-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='authority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uuid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
