# Generated by Django 2.0.7 on 2018-08-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180811_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pgid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Group'),
            preserve_default=False,
        ),
    ]
