# Generated by Django 2.0.7 on 2018-08-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_userinfo_pgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pgid',
            field=models.ForeignKey(on_delete=models.SET(-1), to='db.Group'),
        ),
    ]
