# Generated by Django 2.0.7 on 2018-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20180812_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pgid',
            field=models.IntegerField(default=-1),
        ),
    ]
