# Generated by Django 2.0.7 on 2018-08-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20180812_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.UserInfo'),
            preserve_default=False,
        ),
    ]
